### ISSUE TITLE
Do you mind if I add a TypeScript definition to this project?

### ISSUE THREAD

**Issue by xiaoxiangmoe** [iximiuz/node-diskusage-ng#1]
Do you mind if I add a TypeScript definition to this project?

If you don’t mind, I will create a PR as soon as possible.

**Comment by iximiuz** [comment]
Hi @xiaoxiangmoe, of course, I don't mind. Please go ahead and I'll be happy to merge it!

**Comment by xiaoxiangmoe** [comment]
@iximiuz Can you publish a new version package with types?

**Comment by iximiuz** [comment]
Hi @xiaoxiangmoe, I just published a new version.

**Comment by xiaoxiangmoe** [comment]
Thank you.
