### ISSUE TITLE
Failure to parse output of the df command with spaces in the Filesystem column

### ISSUE THREAD

**Issue by YDKK** [iximiuz/node-diskusage-ng#7]
Hi.
I noticed that if a Filesystem column in the output of the df command contains whitespace characters, parsing fails.

An example of the output of the df command is as follows.

```
Filesystem                      1024-blocks        Used  Available Capacity Mounted on
//example.com/Some Storage/Test 17179803648 15080666092 2099137556      88% /mnt/test
```

This is the output of the df command when mounting a CIFS (Windows share) whose path contains spaces.

**Comment by iximiuz** [comment]
Thanks for the report! I released a new version (v1.0.3).
